export const LOGIN_USER = 'login_user'
export const REGISTER_USER = 'register_user'
export const AUTH_USER = 'auth_user'
export const LOGOUT_USER = 'logout_user'
export const ADD_TO_CART_USER = 'add_to_cart_user'

export const GET_PRODUCTS_BY_SELL = 'get_product_by_sell'
export const GET_PRODUCTS_BY_ARRIVAL = 'get_product_by_arrival'
export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
export const GET_BRANDS = 'get_brands'
export const GET_WOODS = 'get_woods'
export const ADD_BRAND = 'ADD_BRAND'
export const ADD_WOOD = 'ADD_WOOD'